<?php $title = ___('Your Downline tree'); $this->setLayout('member/layout.phtml');
$this->headLink()->appendStylesheet($this->_scriptCss('aff.css'));
echo $this->blocks('aff/top');
?>
<style>
li {
  list-style-type: none !important;
  padding: 0px !important;
}
.css-treeview ul {
  margin: 0px;
}
.grid-container {
  padding : 5px;
}
.css-treeview
{
    list-style: none;

}
.css-treeview li
{
    padding-left : 10px !important;

}


/* Align the label and provide a pointer cursor. */
.css-treeview label
{
    display: inline;
    vertical-align: middle;
    cursor: pointer;
}

/* Highlight selected nodes. */
.css-treeview label.selected
{
    background-color: #08C;
    color: white;
    padding: 2px;
}

/* Hide child nodes of an unchecked expander. */
.css-treeview input.expander ~ ul
{
    display: none;
}

/* Show child nodes of a checked expander. */
.css-treeview input.expander:checked ~ ul
{
    display: block;
}

/* Hide the expander checkbox. */
.css-treeview input.expander
{
    position: absolute;
    opacity: 0;
}


.css-treeview input.expander:disabled
{
    cursor: default;
}

/* Remove the margin from actual checkboxes. */
.css-treeview input.check
{
    margin: 0;
}


.css-treeview input.expander:disabled + span.expander::before
{
    content: "";
    padding-right: 20px;
}


.css-treeview input.expander:enabled + span.expander::before {
    background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAYAAAAbifjMAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEwMPRyoQAAAHtJREFUSEvtlEsKwCAMRHP/S6fYUhDsfETSQnEhrvIcM5NEZsbKWSpuD9cB4mTr70EFDeBAJEBBLACD2AAEeQ+AHLEUMDslQGWBAlRxbZSd17eCa9TrFso3LtxbSN29uqEHM8WwiQjy1Bc5jWq5UhtV8R9z4KaP5mAWcgD5xILE2Y3q1wAAAABJRU5ErkJggg==");
    background-position: 0 0;
    content: "";
    padding-right: 20px;
}


.css-treeview input.expander:checked:enabled + span.expander::before
{
    background-position: 1px 16px;
}
</style>
<div class="grid-container">
  <ul class="css-treeview">
    <li>
        <!--The expander checkbox. This will be hidden by having its opacity set to 0. The enabled attribute
        controls whether the expander will be shown, set it to true if there are child elements. The checked
        attribute controls whether the child items are expanded. -->
        <input type="checkbox" class="expander" checked>

        <!-- The expander image will be added to this span and placed over the expander checkbox using the
        ::before css rule. -->
        <span class="expander"></span>

        <!-- Here is the checkbox. This works as normal. -->


        <!-- The tree nodes label. -->
        <label><?= $user->login . ' - ' . $user->name_f . ' ' . $user->name_l ?></label>
        <ul class="css-treeview">
          <?= $tree ?>
        </ul>
        <!-- The child nodes. -->

    </li>
</ul>
</div>
<div id="aff-detail"></div>
